/**
 * render-to-image.ts
 *
 * Renders a receipt or status HTML snippet into a JPEG image via html2canvas.
 *
 * IMPORTANT: Only use system fonts and no external images in the HTML —
 * this ensures html2canvas makes zero network requests, which is required
 * to avoid ERR_URL_SCHEME in MIT App Inventor WebView.
 */

import html2canvas from 'html2canvas';

/** CSS classes shared by all receipt/status images (matches share-receipt.ts styling) */
export const RECEIPT_IMAGE_STYLES = `
  .r-school { font-size: 17px; font-weight: 800; text-align: center; margin-bottom: 3px; color: #1e3a5f; }
  .r-subtitle { text-align: center; font-size: 11px; color: #666; margin-bottom: 18px; }
  .r-divider { border: none; border-top: 1px dashed #ccc; margin: 10px 0; }
  .r-row { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #f0f0f0; }
  .r-label { color: #555; }
  .r-value { font-weight: 600; text-align: right; }
  .r-total { font-size: 15px; font-weight: 800; border-top: 2px solid #1e3a5f; padding-top: 10px; margin-top: 6px; color: #1e3a5f; }
  .r-green { color: #16a34a; }
  .r-red { color: #dc2626; }
  .r-footer { text-align: center; font-size: 10px; color: #aaa; margin-top: 18px; }
  .r-stamp { display: inline-block; border: 2px solid #16a34a; color: #16a34a; font-size: 11px; font-weight: 800; padding: 3px 10px; border-radius: 4px; letter-spacing: 1px; margin-top: 12px; }
`;

/**
 * Renders an HTML snippet (using .r-* classes) to a JPEG base64 string.
 * Returns null if html2canvas fails.
 *
 * The base64 string has NO "data:image/jpeg;base64," prefix — it's raw base64,
 * ready to embed in the AppInventor bridge JSON payload.
 */
export async function renderHtmlToJpegBase64(innerHtml: string): Promise<string | null> {
    const footer = `<div class="r-footer">Generated by SchoolMate Hub · ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
        }</div>`;

    const container = document.createElement('div');
    container.style.cssText = [
        'position:fixed',
        'top:-9999px',
        'left:-9999px',
        'width:380px',
        'padding:24px 20px 28px',
        'background:#ffffff',
        'font-family:-apple-system,Helvetica Neue,Arial,sans-serif',
        'font-size:13px',
        'color:#1a1a1a',
        'box-sizing:border-box',
    ].join(';');

    container.innerHTML = `<style>${RECEIPT_IMAGE_STYLES}</style>${innerHtml}${footer}`;
    document.body.appendChild(container);

    try {
        const canvas = await html2canvas(container, {
            scale: 1.5,          // good quality without excessive file size
            useCORS: false,      // no cross-origin requests
            allowTaint: true,
            backgroundColor: '#ffffff',
            logging: false,
        });

        document.body.removeChild(container);

        // JPEG is ~3–5× smaller than PNG for text/line-art content
        const dataUrl = canvas.toDataURL('image/jpeg', 0.88);
        // Strip the "data:image/jpeg;base64," prefix
        return dataUrl.split(',')[1] ?? null;

    } catch (err) {
        if (document.body.contains(container)) document.body.removeChild(container);
        console.error('[renderHtmlToJpegBase64]', err);
        return null;
    }
}
