/**
 * share-receipt.ts
 *
 * Renders a receipt HTML string into a PNG image using html2canvas,
 * then shares it via the Web Share API (navigator.share with files).
 *
 * On Android WebView / Chrome, the system share sheet opens and the
 * user can pick WhatsApp (or any other app) to send the image.
 *
 * Falls back to: text via navigator.share, or returning 'failed' so the
 * caller can use the AppInventor bridge (setWebViewString) on MIT WebView.
 */

import html2canvas from 'html2canvas';

export interface ReceiptShareOptions {
    /** Inner HTML content of the receipt (same as printContent) */
    receiptHtml: string;
    /** Title shown in the share sheet */
    shareTitle: string;
    /** Fallback text message if image sharing is not supported */
    fallbackText: string;
}

/**
 * Build a styled off-screen receipt DOM element, render it to canvas,
 * convert to a PNG Blob, and share via navigator.share.
 *
 * Returns: 'image' | 'text' | 'failed'
 */
export async function shareReceiptAsImage(opts: ReceiptShareOptions): Promise<'image' | 'text' | 'failed'> {
    // --- 1. Build an off-screen receipt element ---
    const container = document.createElement('div');
    container.style.cssText = `
    position: fixed;
    top: -9999px;
    left: -9999px;
    width: 380px;
    padding: 24px 20px 28px;
    background: #ffffff;
    font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif;
    font-size: 13px;
    color: #1a1a1a;
    box-sizing: border-box;
  `;

    container.innerHTML = `
    <style>
      .r-school { font-size: 17px; font-weight: 800; text-align: center; margin-bottom: 3px; color: #1e3a5f; }
      .r-subtitle { text-align: center; font-size: 11px; color: #666; margin-bottom: 18px; }
      .r-divider { border: none; border-top: 1px dashed #ccc; margin: 10px 0; }
      .r-row { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #f0f0f0; }
      .r-row:last-child { border-bottom: none; }
      .r-label { color: #555; }
      .r-value { font-weight: 600; text-align: right; }
      .r-total { font-size: 15px; font-weight: 800; border-top: 2px solid #1e3a5f; padding-top: 10px; margin-top: 6px; color: #1e3a5f; }
      .r-green { color: #16a34a; }
      .r-red { color: #dc2626; }
      .r-footer { text-align: center; font-size: 10px; color: #aaa; margin-top: 18px; }
      .r-stamp { display: inline-block; border: 2px solid #16a34a; color: #16a34a; font-size: 11px; font-weight: 800; padding: 3px 10px; border-radius: 4px; letter-spacing: 1px; margin-top: 12px; }
    </style>
    ${opts.receiptHtml}
    <div class="r-footer">Generated by SchoolMate Hub · ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
  `;

    document.body.appendChild(container);

    try {
        // --- 2. Render to canvas ---
        const canvas = await html2canvas(container, {
            scale: 2,           // retina quality
            useCORS: true,
            backgroundColor: '#ffffff',
            logging: false,
        });

        document.body.removeChild(container);

        // --- 3. Convert canvas → Blob ---
        const blob = await new Promise<Blob | null>((resolve) => {
            canvas.toBlob((b) => resolve(b), 'image/png', 0.95);
        });

        if (!blob) return 'failed';

        const file = new File([blob], 'receipt.png', { type: 'image/png' });

        // --- 4. Try Web Share API with files (works on Android Chrome & App WebView) ---
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
            await navigator.share({
                title: opts.shareTitle,
                files: [file],
            });
            return 'image';
        }

        // --- 5. Fallback: share without files (text-only via navigator.share) ---
        if (navigator.share) {
            await navigator.share({
                title: opts.shareTitle,
                text: opts.fallbackText,
            });
            return 'text';
        }

        // --- 6. No sharing API available (MIT App Inventor WebView, etc.) ---
        // Return 'failed' — the caller will use AppInventor.setWebViewString bridge.
        return 'failed';

    } catch (err: any) {
        if (document.body.contains(container)) {
            document.body.removeChild(container);
        }
        // User cancelled share — not really a failure
        if (err?.name === 'AbortError') return 'text';
        console.error('[shareReceiptAsImage]', err);
        return 'failed';
    }
}
